#!/bin/sh

#
# Copyright © 2015-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle wrapper for Android - generated by Vibe Code
#
##############################################################################

# Attempt to set APP_HOME

# Resolve the script directory

# Use the maximum available, or set MAX_FD != -1 to use that value.
DEFAULT_MAX_FD=1024

# For Darwin, add a workaround for Java 9+ to work around the https://bugs.openjdk.java.net/browse/JDK-8193674
# This is only needed for Java 9+ on macOS, but it's safe to set for all Java versions
# Only set this if JAVA_HOME is already set
if [ -n "$JAVA_HOME" ]; then
    case "$(uname -s)" in
        Darwin*)
            # Workaround for macOS Java 9+ issue
            export JAVA_OPTS="-Xmx2048m -Djava.security.manager=allow"
            ;;
    esac
fi

# Attempt to set APP_HOME

# Resolve the script directory
APP_PATH=$(
    cd "$(dirname "$0")" >/dev/null
    pwd -P
)

# Use the maximum available, or set MAX_FD != -1 to use that value.
DEFAULT_MAX_FD=1024

# Collect all arguments for the java command, following the shell quoting and substitution rules
# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
JAVA_OPTS="$JAVA_OPTS -Dorg.gradle.appname=$APP_BASE_NAME"

# Determine if we should use the daemon or not
USE_DAEMON=true

# Check if the user has set GRADLE_USER_HOME
if [ -z "$GRADLE_USER_HOME" ]; then
    GRADLE_USER_HOME="$HOME/.gradle"
fi

# Check if the user has set GRADLE_OPTS
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS=""
fi

# Check if the user has set JAVA_HOME
if [ -z "$JAVA_HOME" ]; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Check if JAVA_HOME is valid
if [ ! -d "$JAVA_HOME" ]; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Check if java exists
JAVA_EXE="$JAVA_HOME/bin/java"
if [ ! -f "$JAVA_EXE" ]; then
    echo "ERROR: JAVA_HOME is set to: $JAVA_HOME"
    echo "       but $JAVA_EXE does not exist."
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Check if the Java version is 1.8 or higher
JAVA_VERSION=$("$JAVA_EXE" -version 2>&1 | head -1 | cut -d'"' -f2 | cut -d'.' -f1,2)
if [ "$JAVA_VERSION" -lt "18" ]; then
    echo "ERROR: JAVA_HOME is set to: $JAVA_HOME"
    echo "       but the Java version is $JAVA_VERSION"
    echo "       Gradle requires Java 8 or higher."
    exit 1
fi

# Set the classpath
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Set the main class
MAIN_CLASS=org.gradle.wrapper.GradleWrapperMain

# Set the command line
CMD_LINE="$JAVA_EXE $JAVA_OPTS $GRADLE_OPTS -Dorg.gradle.appname=$APP_BASE_NAME -classpath \"$CLASSPATH\" $MAIN_CLASS $@"

# Execute the command
eval $CMD_LINE
